name: WeeChat - Debian Slim - Stable
on:
  push:
    branches:
      - main
  schedule:
    # 00:00 on Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: "weechat-stable-debian-slim"
  cancel-in-progress: true

jobs:
  build-and-push:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/container-image-ci-base.yml
    with:
      base: debian
      flavor: slim
      build-type: tag
